repos:
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
    -   id: mypy
        exclude: |
          (?x)
            migrations |
            tests|
          ^$

- repo: https://github.com/psf/black
  rev: 21.5b1
  hooks:
  - id: black
    args: ["--line-length", "95", "--skip-string-normalization"]
    exclude: migrations

- repo: https://github.com/pycqa/isort
  rev: 5.8.0
  hooks:
    - id: isort
      args: ["--profile", "black", "--filter-files"]
      exclude: migrations
