# Generated by Django 3.2.3 on 2021-05-16 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qq_id', models.BigIntegerField()),
                ('telegram_id', models.BigIntegerField()),
                ('qq_nickname', models.TextField()),
                ('telegram_username', models.TextField()),
                ('telegram_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id_qq', models.BigIntegerField(blank=True, null=True)),
                ('message_id_tg', models.TextField(blank=True)),
                ('qq_group_id', models.BigIntegerField(help_text='QQ 群号')),
                ('deleted', models.BooleanField(default=False, help_text='是否被撤回')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.user')),
            ],
        ),
        migrations.CreateModel(
            name='GroupCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.BigIntegerField(verbose_name='QQ 群号')),
                ('card', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.user')),
            ],
        ),
    ]
