# Generated by Django 3.2.3 on 2021-05-16 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_id_qq',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id_tg',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='qq_id',
            field=models.BigIntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
